CREATE TABLE diagnostico
(
    id bigserial NOT NULL,
    nome character varying(50) NOT NULL,
    nacionalidade character varying(50) NOT NULL,
    cpf character varying(50) NOT NULL,
    data_nascimento date NOT NULL,
    sexo character(1),
    nome_mae character varying(50) NOT NULL,
    pais_residencia character varying(50) NOT NULL,
    cep character varying(50) NOT NULL,
    endereco character varying(255) NOT NULL,
    ocupacao character varying(50) NOT NULL,  
    data_sintoma date NOT NULL,
    sintoma_apresentado text[] NOT NULL,
    doenca_previa text[],
    historico_viagem character(1),
    contato_suspeito character(1),
    contato_confirmado character(1),
    contato_animal character(1),
    historico_unidade_saude character(1),
    carrinho_sacola_roda character(1),
    convivencia_crianca character(1),
    animal_estimacao character(1),
    carro_particular character(1),
    garagem_residencial character(1),
    contato_idoso_gestante character(1),
    data_diagnostico timestamp with time zone,
    CONSTRAINT diagnostico_pkey PRIMARY KEY (id)
);