CREATE TABLE notificacao
(
    id bigserial NOT NULL,
    data_notificacao timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    -- Identificação
    nome character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    nacionalidade character varying(50) NOT NULL,
    cpf character varying(50) NOT NULL,
    data_nascimento date NOT NULL,
    sus character varying(50),
    siape character varying(50),
    sexo character varying(50) NOT NULL,
    nome_mae character varying(100) NOT NULL,
    telefone character varying(50) NOT NULL,
    pais_residencia character varying(50) NOT NULL,
    cep character varying(50) NOT NULL,
    endereco character varying(255) NOT NULL,
    ocupacao character varying(100) NOT NULL,
    ocupacao_unidade character varying(100),
    raca character varying(50) NOT NULL,
    -- Dados clínicos
    data_sintoma date NOT NULL,
    gestacao_amamentacao character(1) NOT NULL,
    sintomas text[] NOT NULL,
    outros_sintomas character varying(255),
    doencas text[] NOT NULL,
    outras_doencas character varying(255),
    -- Dados de exposição e viagens
    trabalhando_atualmente character(1) NOT NULL,
    linha_frente character(1) NOT NULL,
    forma_trabalho character varying(50) NOT NULL,
    viagem_recente character(1) NOT NULL,
    quantidade_moradores character varying(50) NOT NULL,
    proximidade_idoso_gestante character(1) NOT NULL,
    proximidade_crianca character(1) NOT NULL,
    proximidade_caso_suspeito character(1) NOT NULL,
    proximidade_caso_confirmado character(1) NOT NULL,
    convive_animal_externo character(1) NOT NULL,
    proximidade_animais character(1) NOT NULL,
    carrinho_feira character(1) NOT NULL,
    carro_particular character(1) NOT NULL,
    estacionamento_publico_coletivo character(1) NOT NULL,
    -- Atendimento especializado
    diagnostico_formal character(1) NOT NULL,
    diagnostico_unidade character varying(100),
    historico_internacao character(1) NOT NULL,
    internacao_dias integer,
    exames_internacao text[],
    anexo_raiox character varying(255),
    anexo_tomografia character varying(255),
    historico_intubacao character(1),
    intubacao_dias integer,
    historico_hemodialise character(1),
    hemodialise_dias integer,
    historico_testagem character(1) NOT NULL,
    tipos_testagem text[],
    anexo_swab_pcr character varying(255),
    anexo_teste_rapido character varying(255),
    anexo_dosagem_igmigg character varying(255),
    necessidade_especifica character(1) NOT NULL,
    necessidade_descricao character varying(255),
    isolamento_social character(1) NOT NULL,
    isolamento_dias integer,
    estado_atual character varying(50) NOT NULL,
    CONSTRAINT diagnostico_pkey PRIMARY KEY (id)
);